name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled
    branches:
      - master
      - production

permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'requires-review') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: piyushkukrejaivs/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: ""
